name = "lustre_dev_tools"
version = "1.0.0"

description = "Lustre's official CLI and development tooling."
repository = { type = "github", user = "lustre-labs", repo = "dev-tools" }
licences = ["MIT"]

links = [
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = ["lusre_dev_tools", "lusre_dev_tools/*"]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
glint = "0.16.0"
spinner = "~> 1.1"
gleam_package_interface = "~> 1.0"
tom = "~> 0.3"
gleam_erlang = "~> 0.25"
gleam_otp = "~> 0.10"
fs = "~> 8.6"
gleam_community_ansi = "~> 1.4"
filepath = "~> 0.1"
simplifile = "~> 1.5"
gleam_json = "~> 1.0"
argv = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
